### PR TITLE
added example for using cloud-controller manager

### LINKED ISSUE #16: Octavia usage
Hello,
Is it possible to define ` use_octavia = true ` as defined on the original terraform-openstack-rke repo ?
https://github.com/remche/terraform-openstack-rke/blob/master/modules/rke/main.tf#L158-L160
I couldn't find anything related with LBAAS or Octavia on this repo.

Thanks
Francisco

### PR DESCRIPTION
**Pull request by dhrp**
This example add the ability to use the cloud-controller-manager; and enable ensuring Octavia LoadBalancers can be created. 

I tested it on Leafcloud, and found that all three floating-subnet-id, floating-network-id and subnet-id are required. In this example I set them manually. I could not quite manage to get these into the system in an elegant way. If @remche can give a pointer I'm happy to improve.

Also note that we need to disable the default rke-cloud-controller-manager to prevent conflicts.

closes #16

### CODE REVIEW

**Comment by remche** [comment]
@dhrp big thanks for your work on this !

- In [CCM](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#load-balancer) documentation, setting floating-subnet-id, floating-network-id and subnet-id seems optionnal. Did you try not setting it and using K8s service annotation ?
- Could you please write down few words on a README to introduce the code ?

**Comment by dhrp** [comment]
@remche, you're welcome! Thank you for the great work on making this whole thing available! 

I've added a README.

And while you are right that you can (probably) add the network annotations to the Service, it's not ideal, as the normal developers workflow and all normal examples expect that they do not need to know this. Is there a way to set it automatically?

**Comment by remche** [comment]
You could probably use `openstack_networking_network_v2` and `openstack_networking_subnet_ids_v2` to retrieve `floating_network_id` and`floating_subnet_id` though.
For `subnet_id` case, I bet it strongy depends on Octavia deployment and seems to be mandatory.. I would need access to an Octavia enabled cloud to do some tests.

**Comment by dhrp** [comment]
Ok, thanks for the tips. I actually found the things, and have tested it to work all now. -- Had to make one additional output on the controller. 

If you want to test it, I'd also be happy to set you up with a test account on Leafcloud. Just sign up on www.leaf.cloud with 'remche' as project name and I'll pick you out.

**Comment by remche** [comment]
@dhrp I just registered, thanks !!

**Comment by remche** [comment]
I did some tests and had to add a security group rule to allow traffic from LB to nodeport in order to have it working out of the box.
I did few other cosmetic changes.

As it seems that I cant push on your PR branch I did it on `dhrp-master`. Would you mind cherry-picking/pushing the changes and checking everything is OK on your side ? Thanks !

**Comment by dhrp** [comment]
Thanks for testing! And thanks a lot. I had tested the Loadbalancers to come up nicely, but had forgotten that security group rule.

**Pull request merged**
