### PR TITLE
Update cloud-init.yml.tpl

### PR DESCRIPTION
**Pull request by ctr26**
Add nfs, cifs (hopefully)

### CODE REVIEW

**Comment by remche** [comment]
@ctr26 thanks for that PR !
I'm not really comfortable with adding such hard dependencies in base code, it should go in image building step IMHO.

A solution could be to implement an optional packages installation via a tf variable though.

**Comment by ctr26** [comment]
That makes more sense agree! I'll have a go

**Comment by ctr26** [comment]
Added your suggestion, I don't know how to test if it works without using your gitlab deployment script. Any tips?

**Comment by powellchristoph** [comment]
> @ctr26 thanks for that PR ! I'm not really comfortable with adding such hard dependencies in base code, it should go in image building step IMHO.
> 
> A solution could be to implement an optional packages installation via a tf variable though.

@remche I agree with you about adding unnecessary deps. But, I think that it would be very nice to be able to extend the cloud-init file. I might investigate it soon if I get some time.

**Comment by ctr26** [comment]
@remche, I can confirm that this PR does install the cloud-init packages correctly (using jsonencode). Are there any style changes you'd prefer?

**Comment by ctr26** [comment]
I haven't checked it in the case on no additional packages though.

**Comment by remche** [comment]
@ctr26 I would prefer that default value for `cloud_init_packages` stays an empty array  : once again I dont want to add such dependencies for default deployment.

@powellchristoph I agree that we should think about a merge functionality on cloud-init file. I already had some discussion with some users about this. I think a yamldecode / merge / yamlencode could do the trick ?

**Comment by ctr26** [comment]
I've emptied the defaults. Thanks

**Comment by ctr26** [comment]
@remche I used jsonencode because apparently yaml encoder is quite experimental, and json works fine in yaml anyway

**Comment by remche** [comment]
@ctr26 the actual PR gives an cloud-init error because yaml is invalid when array is empty.

```
2022-05-17 12:27:10,055 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 2 column 11: "while constructing a mapping
  in "<unicode string>", line 2, column 11:
    packages: {{ $cloud_init_packages }}
              ^
found unhashable key
  in "<unicode string>", line 2, column 12:
    packages: {{ $cloud_init_packages }}
               ^"
2022-05-17 12:27:10,055 - util.py[WARNING]: Failed at merging in cloud config part from part-001
2022-05-17 12:27:10,055 - util.py[DEBUG]: Failed at merging in cloud config part from part-001
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/handlers/cloud_config.py", line 140, in handle_part
    self._merge_part(payload, headers)
  File "/usr/lib/python3/dist-packages/cloudinit/handlers/cloud_config.py", line 116, in _merge_part
    (payload_yaml, my_mergers) = self._extract_mergers(payload, headers)
  File "/usr/lib/python3/dist-packages/cloudinit/handlers/cloud_config.py", line 95, in _extract_mergers
    mergers_yaml = mergers.dict_extract_mergers(payload_yaml)
  File "/usr/lib/python3/dist-packages/cloudinit/mergers/__init__.py", line 79, in dict_extract_mergers
    raw_mergers = config.pop('merge_how', None)
AttributeError: 'NoneType' object has no attribute 'pop'
```

**Comment by ctr26** [comment]
Added an empty string and that looks like it's working on my end

**Comment by ctr26** [comment]
The yamlencode and merge is really smart! I'll test it now.

**Comment by remche** [comment]
note that this solution wont do a deep merge. actually digging Invicton-Labs/terraform-null-deepmerge to allow it.

**Comment by ctr26** [comment]
`custom_cloud_config = "${path.root}/cloud_init.yaml"`

Is working for me. One note I'd make is maybe call it `custom_cloud_config_path` I immediately tried base64 encoding the file without checking the defaults to see.

**Comment by remche** [comment]
@powellchristoph @ctr26 
I would like to have your feedback on this.

- the custom-cloud-init branch use a hack with yamencode/merge that wont allow to merge `runcmd` and `write_files`. a workaround could be to implement a mechanism to make it possible...
- using  Invicton-Labs/terraform-null-deepmerge adds a dependency and wont merge everything nicely because it does not merge lists (only maps).

 I have a preference for the former. What's your take on this ?

**Pull request closed without merging**
