### PR TITLE
Rke2 config change

### PR DESCRIPTION
**Pull request by powellchristoph**
Move the `file` function out of the module. This will allow templated file contents to be passed rather than a straight yaml file.
Change `rke2_config_file` to `rke2_config`.
```
# old
rke2_config_file = "server.yaml"

# new
rke2_config      = file("server.yaml")
rke2_config      = templatefile("${path.module}/files/controlplane.tpl", somevars)
```

### CODE REVIEW

**Comment by remche** [comment]
@powellchristoph thanks for the PR, it makes sense to me.
Do you have any relevant usecase to add in `examples` directory ?

**Comment by powellchristoph** [comment]
I updated one of the existing examples.

**Comment by remche** [comment]
I saw this, I will merge ASAP, thanks again !

**Comment by remche** [comment]
Thanks for this contribution that makes this module better ! 
:partying_face:

**Pull request merged**
